#!/bin/sh /etc/rc.common
START=99
STOP=12
USE_PROCD=1
start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/zbt-5g-adaptive
	procd_set_param respawn 600 5 0
	procd_set_param term_timeout 15
	procd_close_instance
}
