#!/bin/sh /etc/rc.common
USE_PROCD=1
START=96
STOP=01
speedify_enabled() {
	[ "$(uci -q get speedify_bootstrap.main.enabled)" = 1 ]
}

start_service() {
	speedify_enabled || return 0
	procd_open_instance
	procd_set_param command /usr/sbin/zbt-speedify-guard
	procd_set_param respawn 120 10 0
	procd_close_instance
}
