#!/bin/sh /etc/rc.common
USE_PROCD=1
START=96
STOP=01

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/zbt-speedify-guard
	procd_set_param respawn 120 10 0
	procd_close_instance
}
