#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=9

start_service() {
	procd_open_instance guard
	procd_set_param command /usr/sbin/zbt-adguard-guard
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
