#!/bin/sh

[ -f /etc/config/zbt_apps ] || cp /rom/etc/config/zbt_apps /etc/config/zbt_apps
[ -f /etc/config/zbt_adguard ] || cp /rom/etc/config/zbt_adguard /etc/config/zbt_adguard

/etc/init.d/zbt-adguard enable
/etc/init.d/zbt-adguard-guard enable

exit 0
